name: Make a release

on:
  release:
    types: [published, created, edited]
  push:
    branches: [develop]
    

jobs:
  blue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload blue artifact
        uses: actions/upload-artifact@v1
        with:
          name: blue
          path: blue_artifact
        
  red:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload red artifact
        uses: actions/upload-artifact@v1
        with:
          name: red
          path: red_artifact        
        
